### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by eeric** [danieltan07/learning-to-reweight-examples#6]
LeNet model used,
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/optimizer.py", line 38, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

why?

**Comment by danieltan07** [comment]
@eeric I am not sure. May I ask what version of pytorch you are using. It works fine on mine.

**Comment by hansbu** [comment]
it should be:
optimizer = optim.SGD(model.params(), lr=args.lr, momentum=args.momentum)

use model.params() instead of model.parameters()

**Comment by hackershi** [comment]
model.params() works, but why, what's the difference

**Comment by LindgeW** [comment]
If Adam optimizer is used,  how to change ? @hansbu @hackershi @danieltan07

**Comment by Sean-asc** [comment]
Got the same problem. If Adam optimizer is used, how to change ? @hansbu @hackershi @danieltan07
